services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bi-amazon-frontend
    restart: unless-stopped
    ports:
      - "6184:6184"
    extra_hosts:
      - "host.docker.internal:host-gateway"
